server:
  port: ${server.port}

secret:
  key: home-banking-secret-key

spring:
  application:
    name: authentication
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://${postgres.postgresql.service.host}:${postgres.postgresql.service.port}/${postgresql.database}
    username: ${postgresql.user}
    password: ${postgresql.password}
  database:
    driverClassName: org.postgresql.Driver

