server:
  port: 8080

spring:
  application:
    name: user-service
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:postgresql://${postgres.postgresql.service.host}:${postgres.postgresql.service.port}/${postgresql.database}
    username: ${postgresql.user}
    password: ${postgresql.password}
  database:
    driverClassName: org.postgresql.Driver

  kafka:
    bootstrap-servers: ${spring.kafka.producer.bootstrap-servers}
    topic:
      name: USER_TOPIC
    consumer:
      group-id: USER_GROUP_ID