server:
  port: 8085

spring:
  application:
    name: transaction-service
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  database:
    driverClassName: org.postgresql.Driver

  security:
    basic:
      enabled: false